import React, {useState, useEffect } from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Houses from '../components/Houses'
import Image from 'next/image'


export default function Home({data}) {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>DTT Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dtt.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;0,600;0,700;1,500&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"/>  
      </Head>

      <main>
  
        <Houses data = {data}/> 
    
        {/* {console.log(data)} */}

 
       
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export async function getStaticProps() {
  var myHeaders = new Headers();
  myHeaders.append("X-Api-Key", "wrGyPvn6VagYhAqEeFOpuZ1cKdtWUm24");

  var requestOptions = {
    method: "GET",
    headers: myHeaders,
    redirect: "follow",
  };

  const data = await fetch(
    "https://api.intern.d-tt.nl/api/houses",
    requestOptions
  )
    .then((response) => response.json())
    .catch((error) => console.log("error", error));

  return {
    props: {
      data
    },
  };
}